accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.admin.views.decorators import staff_member_required

from accounts.views import (AccountsView,
                            GenerateContractView,
                            TransactionsView,
                            CreateInvoicesView,
                            TransactionsByMonthView,
                            GetTransactionFileView,
                            CustomInvoiceView)
app_name = 'accounts'

urlpatterns = [
    path('', staff_member_required(AccountsView.as_view()), name="home"),
    path('contract/<int:id>/', staff_member_required(GenerateContractView.as_view()), name="generate_contract"),
    path('contract/<int:id>/custominvoice/', staff_member_required(CustomInvoiceView.as_view()), name="generate_custom_invoice"),
    path('transaction/file/<int:id>/', staff_member_required(GetTransactionFileView.as_view()), name="get_transaction_file"),
    path('transactions/', staff_member_required(TransactionsView.as_view()), name="transactions_view"),
    path('transactions/<int:year>/<int:month>/',
         staff_member_required(TransactionsByMonthView.as_view()),
         name="transactions_by_month_view"),
    path('invoices/create/', staff_member_required(CreateInvoicesView.as_view()), name="create_invoices"),
    path('invoices/create/done/',
         staff_member_required(TemplateView.as_view(template_name='accounts/create_invoices_done.html')),
         name="create_invoices_done"),
    ]

blog/urls.py
from django.urls import path

from blog import views as blog_views
from blog.feeds import LatestNews

app_name = 'blog'

urlpatterns = [
    path('', blog_views.HomeView.as_view(), name="uutiset"),
    path('feed/', LatestNews(), name="feed"),
    path('<post_slug>', blog_views.PostView.as_view(), name="post")
]

kollektiivi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
    
from kollektiivi.views import HomeView, PageView, MembersView, MemberProfileView

app_name = 'kollektiivi'

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
    ]

urlpatterns += i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('jäseniä/', MembersView.as_view(), name="members"),
    path('jäseniä/<str:slug>/', MemberProfileView.as_view(), name="member_profile"),
    path('uutiset/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:slug>/', PageView.as_view(), name="page"),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
import datetime
from django import forms
from dateutil.relativedelta import relativedelta

from accounts.models import Contract


def set_due_date():
    now = datetime.datetime.now()
    due_date = now + relativedelta(day=31)
    return datetime.datetime(due_date.year, due_date.month, due_date.day)

def set_title():
    now = datetime.datetime.now()
    next_month = now + relativedelta(months=1)
    desc = "Palvelupaketti {month}/{year} (service fee)".format(month=next_month.month, year=next_month.year)
    return desc


class InvoicesForm(forms.Form):
    issue_date = forms.CharField(max_length=100, initial=datetime.datetime.now().strftime('%d.%m.%Y') )
    due_date = forms.CharField(max_length=100, initial=set_due_date().strftime('%d.%m.%Y'))
    title = forms.CharField(max_length=100, initial = set_title())
    ref_nos = forms.CharField(max_length=200)
    send_to = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                             queryset=Contract.objects.filter(active=True))
    email = forms.BooleanField(initial=False, required=False)
    email_subject = forms.CharField(max_length=200, required=False)
    email_body = forms.CharField(max_length=500, required=False)


class CustomInvoiceForm(forms.Form):
    to_name = forms.CharField(max_length=100)
    to_address = forms.CharField(max_length=200, required=False)
    to_ytunnus = forms.CharField(max_length=200, required=False)
    invoice_date = forms.CharField(max_length=100, initial=datetime.datetime.now().strftime('%d.%m.%Y'))
    invoice_title = forms.CharField(max_length=200)
    due_date = forms.CharField(max_length=100, initial=datetime.datetime.now().strftime('%d.%m.%Y'))
    ref = forms.CharField(max_length=100)

    description_1 = forms.CharField(max_length=100)
    amount_ex_alv_1 = forms.DecimalField()
    amount_alv_rate_1 = forms.DecimalField()

    description_2 = forms.CharField(max_length=100, required=False)
    amount_ex_alv_2 = forms.DecimalField(required=False)
    amount_alv_rate_2 = forms.DecimalField(required=False)

    description_3 = forms.CharField(max_length=100, required=False)
    amount_ex_alv_3 = forms.DecimalField(required=False)
    amount_alv_rate_3 = forms.DecimalField(required=False)

accounts/views.py
import calendar
import os
import tempfile

from decimal import Decimal
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from django.conf import settings
from django.core.files import File
from django.db.models import Sum
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView, ListView, FormView

from wkhtmltopdf.views import PDFTemplateView, PDFTemplateResponse

from accounts.models import Transaction, Contract, Config
from accounts.forms import InvoicesForm, CustomInvoiceForm
from accounts.utils import send_invoice_email

from kollektiivi.signals import site_tracker


class AccountsView(TemplateView):

    template_name = 'accounts/index.html'

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['deposit_balance'] = Contract.get_total_deposit_held() - Decimal(Config.get("vr_deposit"))
        context['funds_booked_balance'] = Transaction.get_booked_balance()
        context['funds_available'] = context['funds_booked_balance'] - context['deposit_balance']
        context['funds_pending'] = Transaction.get_pending_balance()
        context['total_deposit_held'] = Contract.get_total_deposit_held()
        context['total_m2_rented'] = Contract.get_total_m2_rented()
        context['total_monthly_invoices_ex_alv'] = Contract.get_total_monthly_invoices_ex_alv()
        context['total_monthly_invoices_inc_alv'] = Contract.get_total_monthly_invoices_inc_alv()
        context['contracts'] = Contract.objects.filter(active=True).order_by('name')
        context['pending_transactions'] = Transaction.objects.filter(on_statement=False).order_by('-date')
        context['transaction_months'] = Transaction.objects.filter(on_statement=True).dates('date', 'month', order='DESC')
        return context

class TransactionsView(ListView):

    template_name = 'accounts/transactions.html'
    paginate_by = 50

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        qs = Transaction.objects.all().order_by('-date')
        return qs

class GetTransactionFileView(TemplateView):

    def get(self, request, *args, **kwargs):
        id = kwargs['id']
        transaction = Transaction.objects.get(pk=id)
        # Construct the full path to the media file
        path = os.path.join(settings.ACCOUNTS_FILES_LOCATION, transaction.file.name)

        # Serve the file
        with open(path, 'rb') as file:
            response = HttpResponse(file.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline; filename={filename}'.format(filename=transaction.file.name)
        return response

class TransactionsByMonthView(TemplateView):

    template_name = 'accounts/transactions_by_month.html'

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        year = kwargs['year']
        month = kwargs['month']

        consulting = Transaction.objects.filter(date__month=month, date__year=year, on_statement=True).order_by('date')

        data = []

        for c in consulting:
            obj = {'transaction': c, 'balance': Transaction.get_balance_at_date(c.date)}
            data.append(obj)

        start_date = datetime(year, month, 1, 23, 59, 59) - timedelta(days=1)
        end_date = datetime(year, month, calendar.monthrange(year, month)[1], 23, 59, 59)

        opening_balance = Transaction.get_balance_at_date(start_date)
        closing_balance = Transaction.get_balance_at_date(end_date)

        totals = consulting.aggregate(total_credit=Sum("credit"),
                                      total_debit=Sum("debit"),
                                      total_alv_charged=Sum('sales_tax_charged'),
                                      total_alv_paid=Sum('sales_tax_paid'))

        context['data'] = data
        context['opening_balance'] = opening_balance
        context['closing_balance'] = closing_balance
        context['start_date'] = datetime(year, month, 1)
        context['end_date'] = end_date
        context['totals'] = totals

        if end_date.month == datetime.now().month and end_date.year == datetime.now().year:
            context['deposit_balance'] = Contract.get_total_deposit_held() - Decimal(Config.get("vr_deposit"))
            context['funds_available'] = closing_balance - context['deposit_balance']

        return context

class CreateInvoicesView(FormView):

    template_name = 'accounts/create_invoices.html'
    form_class = InvoicesForm
    success_url = "done/"

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        now = datetime.now()
        next_month = now + relativedelta(months=1)
        due_date = (now + relativedelta(day=31)).strftime("%d.%m.%Y")
        email_subject = "Kollektiivi Lasku - {date}".format(date=next_month.strftime("%B %Y"))
        self.initial = {
            'email_subject': email_subject,
            'email_body': "Due Date: {date}".format(date=due_date)
        }

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            invoice_date = form.cleaned_data['issue_date']
            due_date = form.cleaned_data['due_date']
            title = form.cleaned_data['title']
            send_to_ids = form.cleaned_data['send_to']
            ref_nos = form.cleaned_data['ref_nos'].split(',')
            template = 'accounts/invoice_template.html'

            tempdate = datetime.strptime(due_date, "%d.%m.%Y").date()
            year = tempdate.year
            month = '{:02d}'.format(tempdate.month)


            for idx, invoice in enumerate(send_to_ids):

                context = {
                    'invoice_date': invoice_date,
                    'due_date': due_date,
                    'title': title,
                    'ref': ref_nos[idx],
                    'invoice_info': invoice,
                    'config': Config.get_as_dict()
                }

                # create pdf invoice
                pdf = PDFTemplateResponse(request=self.request,
                                               filename="invoice.pdf",
                                               template=template,
                                               context=context)

                filename = "invoice-{year}-{month}-{name}-{ref}.pdf".format(year=year,
                                                                            month=month,
                                                                            name=invoice.name.lower().replace(" ","-"),
                                                                            ref=ref_nos[idx])
                fp = tempfile.TemporaryFile()
                fp.write(pdf.rendered_content)

                # save to transactions
                transaction = Transaction()
                transaction.description = "Invoice - {name} - {ref}".format(name=invoice.name, ref=ref_nos[idx])
                transaction.credit = invoice.get_monthly_invoice_inc_alv()
                transaction.sales_tax_charged = invoice.get_monthly_invoice_alv()
                transaction.sales_tax_rate = Config.get("alv_rate")
                transaction.file = File(fp, filename)
                transaction.save()
                fp.close()

                # email to user
                if form.cleaned_data['email']:
                    email_subject = form.cleaned_data['email_subject']
                    email_body = form.cleaned_data['email_body']
                    send_invoice_email(invoice.email, email_subject, email_body, transaction.file.path)
            return HttpResponseRedirect(self.success_url)

        return render(request, self.template_name, {"form": form})

class CustomInvoiceView(FormView):
    template_name = 'accounts/custom_invoice.html'
    form_class = CustomInvoiceForm

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        contract = get_object_or_404(Contract, id=kwargs['id'])
        now = datetime.now()
        next_month = now + relativedelta(months=1)
        self.initial = {
            'to_name': contract.name,
            'to_address': contract.address,
            'to_ytunnus': contract.business_id,
            'invoice_title':  "Palvelupaketti {month}/{year} (service fee)".format(month=next_month.month, year=next_month.year),
            'description_1': "Kuukausmaksu",
            'amount_ex_alv_1': contract.get_monthly_invoice_ex_alv(),
            'amount_alv_rate_1': Config.get("alv_rate")
        }

        form = self.form_class(initial=self.initial)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            total_ex_alv = 0
            total_alv = 0
            total_inc_alv = 0
            invoice_lines = []

            for i in range(1,4):
                if form.cleaned_data['description_{i}'.format(i=i)]:
                    line_amount_ex_alv = Decimal(form.cleaned_data['amount_ex_alv_{i}'.format(i=i)])
                    line_amount_alv = line_amount_ex_alv * Decimal(form.cleaned_data['amount_alv_rate_{i}'.format(i=i)]/100)
                    line_amount_inc_alv = round(line_amount_ex_alv + line_amount_alv,2)

accounts/templates/accounts/contracts.html
{% load i18n %}
{% load humanize %}
{% load mathfilters %}
{% block content %}

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>{% trans 'Name' %}</th>
				<th>{% trans 'Deposit held' %}</th>
				<th>m<sup>2</sup></th>
				<th>{% trans 'Monthly invoice<br/>(ex ALV)' %}</th>
				<th>{% trans 'Monthly invoice<br/>(inc ALV)' %}</th>
				<th>{% trans 'Actions' %}</th>
			</tr>
		</thead>
		<tbody>
        {% for c in contracts %}
         <tr>
			<td><b>{{ c.name }}</b></td>
			<td class="number">{{ c.deposit_held }} &euro;</td>
			<td class="number">{{ c.meters_sq }} m<sup>2</sup></td>
			<td class="number">{{ c.get_monthly_invoice_ex_alv|floatformat:"2g" }} &euro;</td>
			 <td class="number">{{ c.get_monthly_invoice_inc_alv|floatformat:"2g" }} &euro;</td>
			 <td><a href="{% url 'admin:accounts_contract_change' c.id %}">{% trans 'Edit' %}</a>
				 | <a href="{% url 'accounts:generate_contract' c.id %}">{% trans 'Contract PDF' %}</a>
			 | <a href="{% url 'accounts:generate_custom_invoice' c.id %}">{% trans 'Custom Invoice' %}</a></td>
		</tr>
        {% endfor %}
		 <tr>
			<td><b>{% trans 'Totals' %}</b></td>
			<td class="number"><b>{{ total_deposit_held }} &euro;</b></td>
			<td class="number"><b>{{ total_m2_rented }} m<sup>2</sup></b></td>
			<td class="number"><b>{{ total_monthly_invoices_ex_alv|floatformat:"2g" }} &euro;</b></td>
			 <td class="number"><b>{{ total_monthly_invoices_inc_alv|floatformat:"2g" }} &euro;</b></td>
			 <td></td>
		</tr>
        </tbody>
</table>
</div>


{% endblock %}

accounts/templates/accounts/create_invoices.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}

{% include "accounts/includes/accounts_header.html" %}
<form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

accounts/templates/accounts/create_invoices_done.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}

{% include "accounts/includes/accounts_header.html" %}

<h2>Done - Invoices sent</h2>
{% endblock %}

accounts/templates/accounts/custom_invoice.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}

{% include "accounts/includes/accounts_header.html" %}
<form method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

accounts/templates/accounts/custom_invoice_template.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% trans 'Lasku' %}</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'includes/bootstrap-4.6.2.min.css' %}" type="text/css"/>
     <link href="{% static 'kollektiivi/style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container">
    <table width="100%">
        <tr>
            <td width="60%" class="invoice-align-top">
               <img src="{% static 'kollektiivi/images/kollektiivi-logo-50px.png' %}" style="padding: 0">
            </td>
            <td width="40%" align="right">
                   {{ config.org_name }}
                    <p>{{ config.org_address }}</p>
                    <p>{{ config.contact_email }}<br/>
                    {{ config.contact_phone }}</p>
                    <p>Y-tunnus: {{ config.y_tunnus }}</p>
            </td>

        </tr>
    </table>


<h1 style="text-align:center; margin-bottom:50px;">Lasku</h1>
<table width="100%">
    <tr>
        <td class="invoice-align-top">
            <b>{{ to_name }}</b><br/>
            {{ to_address|safe }}<br/>
            {% if to_ytunnus %}
                Y-tunnus: {{ to_ytunnus }}<br/>
            {% endif %}
        </td>
        <td class="invoice-align-top">
            <strong>Laskun päiväys</strong><br/>
            {{ invoice_date }}
        </td>
        <td class="invoice-align-top">
            <strong>Eräpäivä</strong><br/>
            {{ due_date }}<br/>
            <br/>
            <strong>Viite #</strong><br/>
            {{ ref }}
        </td>
    </tr>

</table>

<h2>{{ invoice_title }}</h2>

<table width="100%">
    <tr>
        <td class="invoice-table-header">Tuote</td>
        <td class="invoice-table-header-right">Hinta</td>
        <td class="invoice-table-header-right">ALV %</td>
        <td class="invoice-table-header-right">Hinta sis. ALV</td>
        <td class="invoice-table-header-right">Yhteensä</td>
    </tr>

    {% for il in invoice_lines %}
        <tr>
            <td class="">{{ il.description }}</td>
            <td class="invoice-align-right">{{ il.amount_ex_alv }} &euro;</td>
            <td class="invoice-align-right">{{ il.amount_alv_rate }}%</td>
            <td class="invoice-align-right">{{ il.amount_inc_alv }} &euro;</td>
            <td class="invoice-align-right">{{ il.amount_inc_alv }} &euro;</td>
        </tr>
    {% endfor %}
    <tr>
        <td colspan="4" class="invoice-table-header-right">Yhteensä veroton</td>
        <td class="invoice-align-right">{{ total_ex_alv }} &euro;</td>
    </tr>

    <tr>
        <td colspan="4" class="invoice-table-header-right">ALV {{ config.alv_rate }}%</td>
        <td class="invoice-align-right">{{ total_alv }} &euro;</td>
    </tr>

    <tr>
        <td colspan="4" class="invoice-table-header-right">Yhteensä</td>
        <td class="invoice-table-header-right">{{ total_inc_alv }} &euro;</td>
    </tr>
</table>



<h2>Maksutiedot</h2>

<table width="100%">
    <tr>
        <td class="invoice-table-header-left">Vastaanottajan nimi</td>
        <td class="invoice-table-header-left">IBAN/BIC</td>
        <td class="invoice-table-header-left">Viite #</td>
    </tr>
    <tr >
        <td class="invoice-align-top">{{ config.org_name }}</td>
        <td class="invoice-align-top">{{ config.account_iban }}<br/>{{ config.account_bic }}</td>
        <td class="invoice-align-top">{{ ref }}</td>
    </tr>
</table>



    <div style="text-align:center; margin-top:100px;">
        Y-tunnus (Business ID & ALV no) - {{ config.y_tunnus }}
    </div>
</div>
</body>
</html>

accounts/templates/accounts/index.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_head_title %}
{% trans "Accounts & Contracts" %}
{% endblock extra_head_title %}

{% block content %}

{% include "accounts/includes/accounts_header.html" %}

<h3>{% trans "Actions" %}</h3>

<a href="{% url 'admin:accounts_transaction_add' %}">{% trans "Add transaction" %}</a>
|
<a href="{% url 'accounts:transactions_view' %}">{% trans "View all transactions" %}</a>
|
<a href="{% url 'accounts:create_invoices' %}">{% trans "Generate Monthly Invoices" %}</a>

<h3>{% trans "Overview" %}</h3>

{% include "accounts/overview.html" %}

<h3>{% trans "Monthly Accounts" %}</h3>

<ul>
{% for tm in transaction_months %}
    <li><a href="{% url 'accounts:transactions_by_month_view' tm.year tm.month %}">{{ tm|date:"M Y" }}</a></li>
{% endfor %}
</ul>

<h3>{% trans "Pending Transactions" %}</h3>

{% include "accounts/pending_transactions.html" %}

<h3>{% trans "Contracts" %}</h3>

{% include "accounts/contracts.html" %}

{% endblock %}

accounts/templates/accounts/overview.html
{% load i18n %}
{% load humanize %}
{% load mathfilters %}
{% block content %}

<div class="table-responsive">
	<table class="table table-striped">
		<tbody>
		<tr>
			<td class="header">{% trans 'Funds Available' %}</td>
			 <td class="{% if funds_available < 0%}negative{% endif %}">{{ funds_available|floatformat:"2g" }} &euro;</td>
		</tr>
        <tr>
			<td class="header">{% trans 'Booked Balance' %}</td>
			 <td>{{ funds_booked_balance|floatformat:"2g" }} &euro;</td>
		</tr>
		<tr>
			<td class="header">{% trans 'Deposit Balance' %}</td>
			 <td>{{ deposit_balance|floatformat:"2g" }} &euro;</td>
		</tr>
		<tr>
			<td class="header">{% trans 'Pending Balance' %}</td>
			 <td>{{ funds_pending|floatformat:"2g" }} &euro;</td>
		</tr>
		<tr>
			<td class="header">{% trans 'm2 rented' %}</td>
			 <td>{{ total_m2_rented }} m<sup>2</sup></td>
		</tr>
        </tbody>
</table>
</div>

{% endblock %}

accounts/templates/accounts/pending_transactions.html
{% load i18n %}
{% load humanize %}
{% load mathfilters %}
{% block content %}

{% if pending_transactions %}
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>{% trans 'Date' %}</th>
				<th>{% trans 'Description' %}</th>
				<th>{% trans 'Credit' %}</th>
				<th>{% trans 'Debit' %}</th>
				<th>{% trans 'ALV charged' %}</th>
				<th>{% trans 'ALV Paid' %}</th>
				<th>{% trans 'File' %}</th>
                <th>{% trans 'Actions' %}</th>
			</tr>
		</thead>
		<tbody>
        {% for pt in pending_transactions %}
         <tr>
			<td>{{ pt.date }}</td>
             <td>{{ pt.description }}</b></td>
			<td class="number">{{ pt.credit }} &euro;</td>
			<td class="number">{{ pt.debit}} </td>
			<td class="number">{{ pt.sales_tax_charged }} &euro;</td>
			 <td class="number">{{ pt.sales_tax_paid }} &euro;</td>
			 <td>{% if pt.file %}
				 <a href="{% url 'accounts:get_transaction_file' pt.id %}" target="_blank">{% trans 'View' %}</a>
				 {% endif %}
			 </td>
			 <td><a href="{% url 'admin:accounts_transaction_change' pt.id %}">{% trans 'Edit' %}</a></td>
		</tr>
        {% endfor %}
        </tbody>
</table>
</div>
{% else %}
    {% trans 'No transactions pending' %}
{% endif %}


{% endblock %}

accounts/templates/accounts/transactions.html
{% extends "base.html" %}
{% load i18n %}
{% load admin_urls %}
{% load humanize %}
{% block extra_head_title %}
{% trans "All Transactions" %}
{% endblock extra_head_title %}
{% block content %}

{% include "accounts/includes/accounts_header.html" %}

<h2>{% trans 'All Transactions' %}</h2>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>{% trans 'Date' %}</th>
				<th>{% trans 'Description' %}</th>
				<th class="number">{% trans 'Credit' %}</th>
				<th class="number">{% trans 'Debit' %}</th>
				<th class="number">{% trans 'On Statement' %}</th>
				<th class="number">{% trans 'Options' %}</th>
			</tr>
		</thead>
		<tbody>

{% for t in page_obj %}
 <tr>
	<td>{{ t.date|naturalday  }}</td>
	<td>{{ t.description }}</td>
	<td class="number">{{ t.credit|intcomma }}</td>
	<td class="number">{{ t.debit|intcomma }}</td>
	<td class="number">{{ t.on_statement }}</td>
	<td class="number"><a href="{% url 'admin:accounts_transaction_change' t.id %}">Edit</a></td>
</tr>
{% endfor %}
</tbody>
</table>

{% include "accounts/includes/transaction_nav.html" %}

{% endblock %}