blog/urls.py
from django.urls import path

from blog import views as blog_views
from blog.feeds import LatestNews

app_name = 'blog'

urlpatterns = [
    path('', blog_views.HomeView.as_view(), name="uutiset"),
    path('feed/', LatestNews(), name="feed"),
    path('<post_slug>', blog_views.PostView.as_view(), name="post")
]

kollektiivi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
    
from kollektiivi.views import HomeView, PageView, MembersView, MemberProfileView

app_name = 'kollektiivi'

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
    ]

urlpatterns += i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('jäseniä/', MembersView.as_view(), name="members"),
    path('jäseniä/<str:slug>/', MemberProfileView.as_view(), name="member_profile"),
    path('uutiset/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:slug>/', PageView.as_view(), name="page"),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from tinymce.models import HTMLField

from kollektiivi.models import Tracker


class Post(models.Model):
    display_date = models.DateTimeField(default=timezone.now)
    title = models.TextField(blank=False)
    slug = models.SlugField(blank=True, default=None, max_length=200)
    body = HTMLField()
    image = models.FileField(upload_to="images", blank=True, default=None)
    active = models.BooleanField(default=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   default=None,
                                   on_delete=models.SET_NULL,
                                   related_name="post_created_by")
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   default=None,
                                   on_delete=models.SET_NULL,
                                   related_name="post_updated_by")
    class Meta:
        ordering = ['-display_date']
        verbose_name = _('Uutiset')
        verbose_name_plural = _('Uutiset')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title_fi)
        super(Post, self).save(*args, **kwargs)

    def get_hits(self):
        return Tracker.objects.filter(url__endswith=self.slug).count()

class PostAttachment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    file = models.FileField(upload_to="post_files", blank=False)
    title = models.TextField(blank=False)
    order_by = models.IntegerField(default=0)

    class Meta:
        verbose_name = _('Post Attachment')
        verbose_name_plural = _('Post Attachments')

blog/views.py
from blog.models import Post
from kollektiivi.signals import site_tracker
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView


class HomeView(ListView):

    template_name = 'blog/home.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):

        result_list = Post.objects.filter(active=True).order_by('-display_date')
        return result_list


class PostView(TemplateView):

    template_name = 'blog/post-full.html'

    def get(self, request, *args, **kwargs):
        site_tracker.send(sender=None, request=request)
        preview = request.GET.get("preview", 0)
        if preview == "1":
            self.object = get_object_or_404(Post, slug=kwargs['post_slug'])
        else:
            self.object = get_object_or_404(Post, slug=kwargs['post_slug'], active=True)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog'] = self.object
        return context

blog/templates/blog/blog-full-post.html
{% extends "base.html" %} 
{% load i18n %} 
{% load static %}
{% load thumbnail %}

{% block extra_head_title %}
	{% trans 'Uutiset' %} - {{ blog.title }}
{% endblock extra_head_title %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans 'Kollektiivi' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:uutiset' %}">{% trans 'Uutiset' %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ blog.title }}</li>
  </ol>
</nav>

<div>
{% if blog.image %}
	<a href="{{ blog.image.url }}" data-toggle="lightbox" data-gallery="product-gallery">
  		{% thumbnail blog.image "250x250" format="PNG" padding=True as im %}
	 		<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="thumbnail blog-image" alt="{{ blog.title }}">
  		{% endthumbnail %}
  	</a>
  {% endif %}
	<h1 class="blog">{{ blog.title }}</h1>
	<div class="post-date">{{ blog.display_date|date:"d F Y" }}</div>
  	<div>
  		{{ blog.body|safe }}
  	</div>
  	<div class="clearfix"></div>
</div>
  	

{% endblock %}

blog/templates/blog/feed.html
<p>{{ obj.body|striptags|truncatewords:40 }}</p>

blog/templates/blog/home.html
{% extends "base.html" %} 
{% load i18n %} 
{% load static %}

{% block social_media %}
<meta property="og:title" content="Kollektiivi Joensuu - {% trans 'Uutiset' %}" />
<meta property="og:image" content="https://kollektiivi.org/static/kollektiivi/images/kollektiivi-logo-250px">
<meta property="og:url" content="https://kollektiivi.org{% url 'blog:uutiset' %}"/>
<meta property="og:image:type" content="image/png">
<meta property="og:type" content="website" />
{% endblock social_media %}

{% block extra_head_title %}
	{% trans 'Uutiset' %}
{% endblock extra_head_title %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans 'Kollektiivi' %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% trans 'Uutiset' %}</li>
  </ol>
</nav>

<h1>{% trans 'Uutiset' %}</h1>

{% if page_obj %}
	{% for post in page_obj %}
		{% include "blog/post-row.html" %}
	{% endfor %}
	{% include "blog/pagination.html" %}
{% endif %}

{% endblock %}

blog/templates/blog/pagination.html
{% load i18n %}

{% if page_obj.has_previous or page_obj.has_next %}
<nav>
  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
          <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="{% trans 'Edellinen' %}">
            <span aria-hidden="true" class="fas fa-chevron-left">&lt;&lt;</span>
          </a>
         </li>
      {% endif %}

        {% if page_obj.has_previous %}
        	<li class="page-item">
        		<a class="page-link" href="?page=1">1<span class="sr-only">1</span></a>
        	</li>
        {% endif %}
        {% if page_obj.previous_page_number > 2 %}
        	<li class="page-item">
        		<span class="page-link">...</span>
        	</li>
        {% endif %}
        {% if page_obj.previous_page_number > 1 %}
            <li class="page-item">
            	<a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            		{{ page_obj.previous_page_number }}
            		<span class="sr-only"> {{ page_obj.previous_page_number }}</span>
            	</a>
            </li>
        {% endif %}
        
        <li class="active page-item">
        	<a class="page-link" href="?page={{ page_obj.number }}">
        		{{ page_obj.number }} 
        		<span class="sr-only">{{ page_obj.number }}</span>
        	</a>
        </li>
        {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
            <li class="page-item">
            	<a class="page-link" href="?page={{ page_obj.next_page_number }}">
            		{{ page_obj.next_page_number }}
            		<span class="sr-only"> {{ page_obj.next_page_number }}</span>
            	</a>
            </li>
            {% with page_obj.next_page_number|add:"1" as secondnext_page %}
                {% if secondnext_page != page_obj.paginator.num_pages %}
                    <li class="page-item">
                    	<span class="page-link">...</span>
                    </li>
                {% endif %}
            {% endwith %}
        {% endif %}

      {% if page_obj.has_next %}
      	<li class="page-item">
      		<a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
      			{{ page_obj.paginator.num_pages }}
      			<span class="sr-only"> {{ page_obj.paginator.num_pages }}</span>
      		</a>
      	</li>
      	{% endif %}

    {% if page_obj.has_next %}
        <li class="page-item">
          	<a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="{% trans 'Seuraava' %}">
            	<span aria-hidden="true" class="fas fa-chevron-right">&gt;&gt;</span>
          	</a>
        </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

blog/templates/blog/post-full.html
{% extends "base.html" %} 
{% load i18n %} 
{% load static %}
{% load thumbnail %}

{% block social_media %}
<meta property="og:title" content="Kollektiivi Joensuu - {{ blog.title }}" />
<meta property="og:description" content="{{ blog.body|striptags|truncatewords:75 }}" />
{% if blog.image %}
	<meta property="og:image" content="https://kollektiivi.org{{ blog.image.url }}">
{% else %}
	<meta property="og:image" content="https://kollektiivi.org/static/kollektiivi/images/kollektiivi-logo-250px">
{% endif %}
<meta property="og:url" content="https://kollektiivi.org{% url 'blog:post' blog.slug %}"/>
<meta property="og:image:type" content="image/png">
<meta property="og:type" content="website" />
{% endblock social_media %}

{% block extra_head_title %}
	{% trans 'Uutiset' %} - {{ blog.title }}
{% endblock extra_head_title %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">{% trans 'Kollektiivi' %}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:uutiset' %}">{% trans 'Uutiset' %}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ blog.title }}</li>
  </ol>
</nav>

<div>
{% if blog.image %}
	<a href="{{ blog.image.url }}" data-toggle="lightbox" data-gallery="product-gallery">
  		{% thumbnail blog.image "250x250" format="PNG" padding=True as im %}
	 		<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="thumbnail post-image" alt="{{ blog.title }}">
  		{% endthumbnail %}
  	</a>
  {% endif %}
	<h1 class="blog">{{ blog.title }}</h1>
	<div class="post-date">{{ blog.display_date|date:"j F Y" }}</div>
  	<div>
  		{{ blog.body|safe }}
  	</div>

	{% if blog.postattachment_set %}
		{% trans 'Attachments' %}
		<ul class="news-attachments">
		{% for pa in blog.postattachment_set.all %}
			<li><a target="_blank" href="{{ pa.file.url }}">{{ pa.title }}</a></li>
		{% endfor %}
		</ul>
	{% endif %}

  	<div class="clearfix"></div>
</div>
  	

{% endblock %}

blog/templates/blog/post-row.html
{% load thumbnail %}
{% load i18n %} 

<div class="post-row">
	{% if post.image %}
		{% thumbnail post.image "200x200" format="PNG" padding=True as im %}
		<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="thumbnail post-image" alt="{{ post.title }}">
		{% endthumbnail %}
  	{% endif %}
  	
	<h2 class="post"><a href="{% url 'blog:post' post.slug %}">{{ post.title }}</a> </h2>
	<div class="post-date">{{ post.display_date|date:"j F Y" }}</div>
  	<div>
  		{{ post.body|safe|truncatewords_html:75 }}

		{% if post.postattachment_set %}
			{% trans 'Attachments' %}
			<ul class="news-attachments">
			{% for pa in post.postattachment_set.all %}
				<li><a target="_blank" href="{{ pa.file.url }}">{{ pa.title }}</a></li>
			{% endfor %}
			</ul>
		{% endif %}

		<a href="{% url 'blog:post' post.slug %}">{% trans 'Lue lisää' %}</a>
  	</div>
  	<div class="clearfix"></div>
</div>