blog/urls.py
from django.urls import path

from blog import views as blog_views
from blog.feeds import LatestNews

app_name = 'blog'

urlpatterns = [
    path('', blog_views.HomeView.as_view(), name="uutiset"),
    path('feed/', LatestNews(), name="feed"),
    path('<post_slug>', blog_views.PostView.as_view(), name="post")
]

kollektiivi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
    
from kollektiivi.views import HomeView, PageView, MembersView, MemberProfileView

app_name = 'kollektiivi'

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
    ]

urlpatterns += i18n_patterns(
    path('', HomeView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('jäseniä/', MembersView.as_view(), name="members"),
    path('jäseniä/<str:slug>/', MemberProfileView.as_view(), name="member_profile"),
    path('uutiset/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:slug>/', PageView.as_view(), name="page"),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kollektiivi/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from tinymce.models import HTMLField


class Page(models.Model):
    title = models.CharField(blank=False, max_length=200)
    body = HTMLField(blank=True, null=True, default=None)
    slug = models.SlugField()
    menu_order_by = models.IntegerField(default=0)
    image = models.FileField(upload_to="pages", blank=True, default=None)
    on_menu = models.BooleanField(default=False)
    on_footer = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   default=None,
                                   on_delete=models.SET_NULL,
                                   related_name="page_created_by")
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   default=None,
                                   on_delete=models.SET_NULL,
                                   related_name="page_updated_by")
    class Meta:
        ordering = ['menu_order_by', 'title']
        verbose_name = _('Sivu')
        verbose_name_plural = _('Sivut')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title_fi)
        super(Page, self).save(*args, **kwargs)


class Tag(models.Model):
    name = models.TextField(blank=False, null=False)
    description = HTMLField(blank=True, null=True, default=None)
    slug = models.SlugField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name_fi)
        super(Tag, self).save(*args, **kwargs)


class Member(models.Model):
    name = models.CharField(blank=False, max_length=200)
    strapline = models.CharField(blank=True, null=True, default=None, max_length=200)
    body = HTMLField(blank=True, null=True, default=None)
    slug = models.SlugField()
    order_by = models.IntegerField(default=0)
    photo = models.FileField(upload_to="members", blank=True, default=None)
    active = models.BooleanField(default=False)
    visible = models.BooleanField(default=False)
    contact = HTMLField(blank=True, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   default=None,
                                   on_delete=models.SET_NULL,
                                   related_name="member_created_by")
    updated_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   null=True,
                                   blank=True,
                                   default=None,
                                   on_delete=models.SET_NULL,
                                   related_name="member_updated_by")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Jäsen')
        verbose_name_plural = _('Jäseniä')
        ordering = ['order_by', 'name']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name_fi)
        super(Member, self).save(*args, **kwargs)


class Tracker (models.Model):
    tracker_date = models.DateTimeField(default=timezone.now)
    ip = models.GenericIPAddressField()
    agent = models.TextField(blank=True)
    url = models.TextField(blank=True, null=True, default=None)

    def __str__(self):
        return self.ip

    class Meta:
        verbose_name = _('Tracker')
        verbose_name_plural = _('Trackers')

kollektiivi/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from kollektiivi.models import Page, Tag, Member
from blog import utils


class HomeView(TemplateView):

    template_name = 'kollektiivi/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['page'] = get_object_or_404(Page, slug='etusivu')
        context['news'] = utils.get_posts(3)
        context['members'] = Member.objects.filter(active=True, visible=True)
        return context


class PageView(TemplateView):

    template_name = 'kollektiivi/page.html'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Page, slug=kwargs['slug'], active=True)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = self.object
        return context


class MembersView(TemplateView):

    template_name = 'kollektiivi/members.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['members_current'] = Member.objects.filter(active=True, visible=True)
        context['members_previous'] = Member.objects.filter(active=False, visible=True)
        return context


class MemberProfileView(TemplateView):

    template_name = 'kollektiivi/member-profile.html'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Member, slug=kwargs['slug'], visible=True)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['member'] = self.object
        return context


class TagView(TemplateView):

    template_name = 'kollektiivi/tag.html'

    def get(self, request, *args, **kwargs):
        self.object = get_object_or_404(Tag, slug=kwargs['slug'])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.object
        return context

kollektiivi/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
	
		<!-- Google tag (gtag.js) -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-42CGX4LKEC"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());
		
		  gtag('config', 'G-42CGX4LKEC');
		</script>
		
		<base href="/">
		<title>
			{% trans 'Kollektiivi' %} - {% block extra_head_title %}{% endblock extra_head_title %}
		</title>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<meta name="description" content="{% trans 'Kollektiivi Joensuu - käsityö-, taide- ja työtila Joensuun keskustassa.' %}">
    	<meta name="keywords" content="kollektiivi, joensuu, suomi, paja, finland, osuuskunta, taide, käsityö, työtile, art, craft">
    	<meta name="title" content="Kollektiivi Joensuu">
    	<meta name="author" content="Kollektiivi">
    	
    	<link rel="stylesheet" href="{% static 'includes/bootstrap-4.6.2.min.css' %}" type="text/css"/>
		<script src="{% static 'includes/jquery-3.5.1.slim.min.js' %}"></script>
		<script src="{% static 'includes/bootstrap-4.6.2.bundle.min.js' %}"></script>
    
    	<script src="{% static 'includes/ekko-lightbox-5.3.0.min.js' %}"></script>
    	<link rel="stylesheet" href="{% static 'includes/ekko-lightbox-5.3.0.css' %}" type="text/css"/>
    	<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css"> 
		<link href="{% static "kollektiivi/style.css" %}" rel="stylesheet" type="text/css">
		<script src="{% static "kollektiivi/lightbox.js" %}"></script>
		
		{% block extra_css %}{% endblock extra_css %}
		{% block extra_js %}{% endblock extra_js %}
		
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'kollektiivi/favicons/apple-touch-icon.png' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'kollektiivi/favicons/favicon-32x32.png' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'kollektiivi/favicons/favicon-16x16.png' %}">
		<link rel="manifest" href="{% static 'kollektiivi/favicons/site.webmanifest' %}">
		<link rel="mask-icon" href="{% static 'kollektiivi/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="theme-color" content="#ffffff">
		
		<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url 'blog:feed' %}">
		
		
		{% block social_media %}
		{% endblock social_media %}

	</head>
	<body>
	
	{% include "includes/header.html" %}

	 <div class="container">      
	{% block content %}
	{% endblock content %}
	</div> <!--  end container -->

	{% include "includes/footer.html" %}
 
</body>
</html>